export const USER_INFO = 'USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';

export const FLAG_FORGOT_PASSWORD = 'FLAG_FORGOT_PASSWORD';
export const REMOVE_FLAG_FORGOT_PASSWORD = 'REMOVE_FLAG_FORGOT_PASSWORD'
