export const GET_CONSTRUCTER_DATA: 'GET_CONSTRUCTER_DATA' = 'GET_CONSTRUCTER_DATA';
export const REMOVE_CONSTRUCTER_DATA: 'REMOVE_CONSTRUCTER_DATA' = 'REMOVE_CONSTRUCTER_DATA'
export const FILTER_CONSTRUCTER: 'FILTER_CONSTRUCTER' = 'FILTER_CONSTRUCTER'

export const GET_BUN_DATA: 'GET_BUN_DATA' = 'GET_BUN_DATA';
export const CLEAR_BUN_DATA: 'CLEAR_BUN_DATA' = 'CLEAR_BUN_DATA';
export const CLEAR_CONSTRUCTER_DATA: 'CLEAR_CONSTRUCTER_DATA' = 'CLEAR_CONSTRUCTER_DATA';

export const COUNT_PRICE: 'COUNT_PRICE' = 'COUNT_PRICE';
