export const GET_INGREDIENTS: 'GET_INGREDIENTS' = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';


export const GET_INGREDIENTS_INFO_WITH_KEY_ID: 'GET_INGREDIENTS_INFO_WITH_KEY_ID' = 'GET_INGREDIENTS_INFO_WITH_KEY_ID';