export const GET_INGREDIENTS = 'GET_INGREDIENTS' as const;
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS' as const;
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED' as const;

export const GET_INGREDIENTS_INFO_WITH_KEY_ID = 'GET_INGREDIENTS_INFO_WITH_KEY_ID' as const;