export const SEND_INGREDIENTS: 'SEND_INGREDIENTS' = 'SEND_INGREDIENTS';
export const SEND_INGREDIENTS_SUCCESS: 'SEND_INGREDIENTS_SUCCESS' = 'SEND_INGREDIENTS_SUCCESS';
export const SEND_INGREDIENTS_FAILED: 'SEND_INGREDIENTS_FAILED' = 'SEND_INGREDIENTS_FAILED';
export const CLEAR_ORDER: 'CLEAR_ORDER' = 'CLEAR_ORDER';
