export const SEND_INGREDIENTS = 'SEND_INGREDIENTS' as const;
export const SEND_INGREDIENTS_SUCCESS = 'SEND_INGREDIENTS_SUCCESS' as const;
export const SEND_INGREDIENTS_FAILED = 'SEND_INGREDIENTS_FAILED' as const;
export const CLEAR_ORDER = 'CLEAR_ORDER' as const;
