export const SEND_INGREDIENTS: 'SEND_INGREDIENTS' = 'SEND_INGREDIENTS';
export const SEND_INGREDIENTS_SUCCESS: 'SEND_INGREDIENTS_SUCCESS' = 'SEND_INGREDIENTS_SUCCESS';
export const SEND_INGREDIENTS_FAILED: 'SEND_INGREDIENTS_FAILED' = 'SEND_INGREDIENTS_FAILED';
export const CLEAR_ORDER: 'CLEAR_ORDER' = 'CLEAR_ORDER';

export const CLEAR_CONSTRUCTER_DATA: 'CLEAR_CONSTRUCTER_DATA' = 'CLEAR_CONSTRUCTER_DATA';
export const CLEAR_BUN_DATA: 'CLEAR_BUN_DATA' = 'CLEAR_BUN_DATA';
