export const USER_INFO: 'USER_INFO' = 'USER_INFO';
export const USER_INFO_SUCCESS: 'USER_INFO_SUCCESS' = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILED: 'USER_INFO_FAILED' = 'USER_INFO_FAILED';
export const CLEAR_USER_INFO: 'CLEAR_USER_INFO' = 'CLEAR_USER_INFO';
