export const WS_INIT_CONNECTION: 'WS_INIT_CONNECTION' = 'WS_INIT_CONNECTION';
export const WS_ON_OPEN: 'WS_ON_OPEN' = 'WS_ON_OPEN';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_USER_NAME_UPDATE: 'WS_USER_NAME_UPDATE' = 'WS_USER_NAME_UPDATE';