export const WS_INIT_CONNECTION: 'WS_INIT_CONNECTION' = 'WS_INIT_CONNECTION';
export const WS_ON_OPEN: 'WS_ON_OPEN' = 'WS_ON_OPEN';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const FULL_OBJ_FROM_WS: 'FULL_OBJ_FROM_WS' = 'FULL_OBJ_FROM_WS';

export const WS_INIT_CONNECTION_HISTORY: 'WS_INIT_CONNECTION_HISTORY' = 'WS_INIT_CONNECTION_HISTORY';
export const WS_ON_OPEN_HISTORY: 'WS_ON_OPEN_HISTORY' = 'WS_ON_OPEN_HISTORY';
export const WS_CONNECTION_ERROR_HISTORY: 'WS_CONNECTION_ERROR_HISTORY' = 'WS_CONNECTION_ERROR_HISTORY';
export const WS_CONNECTION_CLOSED_HISTORY: 'WS_CONNECTION_CLOSED_HISTORY' = 'WS_CONNECTION_CLOSED_HISTORY';
export const WS_GET_MESSAGE_HISTORY: 'WS_GET_MESSAGE_HISTORY' = 'WS_GET_MESSAGE_HISTORY';
export const WS_SEND_MESSAGE_HISTORY: 'WS_SEND_MESSAGE_HISTORY' = 'WS_SEND_MESSAGE_HISTORY';
